"""empty message
Revision ID: 898ab6ce876a
Revises:
Create Date: 2020-04-07 12:40:27.815652
"""
from alembic import op
import sqlalchemy as sa
import csv
from sqlalchemy.sql import insert
from sqlalchemy import orm

# revision identifiers, used by Alembic.
revision = '898ab6ce876a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    champs = op.create_table('champions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ChampName', sa.String(length=100), nullable=True),
    sa.Column('AmountOfWins', sa.Integer(), nullable=True),
    sa.Column('AmountOfLosses', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    matches = op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Skin_Id_Winner', sa.Integer(), nullable=True),
    sa.Column('Skin_Id_Loser', sa.Integer(), nullable=True),
    sa.Column('MatchDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    skins = op.create_table('skins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('SkinName', sa.String(length=100), nullable=True),
    sa.Column('SkinImg', sa.String(length=100), nullable=True),
    sa.Column('ReleaseDate', sa.DateTime(), nullable=True),
    sa.Column('RankingScore', sa.Integer(), nullable=True),
    sa.Column('AmountOfWins', sa.Integer(), nullable=True),
    sa.Column('AmountOfLosses', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skins')
    op.drop_table('matches')
    op.drop_table('champions')
    # ### end Alembic commands ###