# Docker meta informatie voor de flask restfull api
FROM python:3.7.4

WORKDIR /srv/flask_app
COPY requirements.txt requirements.txt
RUN pip install -r ./requirements.txt
COPY . .

RUN chmod +x ./start.sh
CMD ["python", "app.py"]